import type { Recipe } from "./types";

const randomRecipes: Recipe[] = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 8,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 20.92,
    extendedIngredients: [
      {
        id: 18369,
        aisle: "Baking",
        image: "white-powder.jpg",
        consistency: "SOLID",
        name: "baking powder",
        nameClean: "baking powder",
        original: "1/4 teaspoon baking powder",
        originalName: "baking powder",
        amount: 0.25,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 18372,
        aisle: "Baking",
        image: "white-powder.jpg",
        consistency: "SOLID",
        name: "baking soda",
        nameClean: "baking soda",
        original: "1 teaspoon baking soda",
        originalName: "baking soda",
        amount: 1.0,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          metric: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
        },
      },
      {
        id: 10019165,
        aisle: "Baking",
        image: "dutch-process-cocoa-powder.png",
        consistency: "SOLID",
        name: "dutch process cocoa",
        nameClean: "dutch processed cocoa powder",
        original: "1/2 cup unsweetened Dutch process cocoa",
        originalName: "unsweetened Dutch process cocoa",
        amount: 0.5,
        unit: "cup",
        meta: ["unsweetened"],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 43.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1123,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg.png",
        consistency: "SOLID",
        name: "egg",
        nameClean: "egg",
        original: "1 large egg",
        originalName: "egg",
        amount: 1.0,
        unit: "large",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "large", unitLong: "large" },
          metric: { amount: 1.0, unitShort: "large", unitLong: "large" },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "wheat flour",
        original: "1 1/4 cups all-purpose flour",
        originalName: "all-purpose flour",
        amount: 1.25,
        unit: "cups",
        meta: ["all-purpose"],
        measures: {
          us: { amount: 1.25, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 156.25, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 19336,
        aisle: "Baking",
        image: "powdered-sugar.jpg",
        consistency: "SOLID",
        name: "icing sugar",
        nameClean: "powdered sugar",
        original: "2 cups sifted icing sugar",
        originalName: "sifted icing sugar",
        amount: 2.0,
        unit: "cups",
        meta: ["sifted"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 240.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "1/4 teaspoon salt",
        originalName: "salt",
        amount: 0.25,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 19335,
        aisle: "Baking",
        image: "sugar-in-bowl.png",
        consistency: "SOLID",
        name: "sugar",
        nameClean: "sugar",
        original: "1 cup sugar",
        originalName: "sugar",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 200.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1145,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "unsalted butter",
        original: "3/4 cup plus 2 tablespoons unsalted butter",
        originalName: "unsalted butter",
        amount: 0.75,
        unit: "cup",
        meta: ["unsalted"],
        measures: {
          us: { amount: 0.75, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 170.25, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 2050,
        aisle: "Baking",
        image: "vanilla-extract.jpg",
        consistency: "LIQUID",
        name: "vanilla extract",
        nameClean: "vanilla extract",
        original: "2 teaspoons vanilla extract",
        originalName: "vanilla extract",
        amount: 2.0,
        unit: "teaspoons",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 2.0, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 4615,
        aisle: "Oil, Vinegar, Salad Dressing;Baking",
        image: "shortening.jpg",
        consistency: "SOLID",
        name: "vegetable shortening",
        nameClean: "shortening",
        original: "1/4 cup vegetable shortening",
        originalName: "vegetable shortening",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 51.25, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    id: 641395,
    title: "Delicious Homemade Chocolate Oreos",
    readyInMinutes: 90,
    servings: 25,
    sourceUrl:
      "http://www.foodista.com/recipe/68TDBVRL/delicious-homemade-chocolate-oreos",
    image: "https://spoonacular.com/recipeImages/641395-556x370.jpg",
    imageType: "jpg",
    summary:
      'You can never have too many dessert recipes, so give Delicious Homemade Chocolate Oreos a try. This recipe serves 25. One serving contains <b>166 calories</b>, <b>1g of protein</b>, and <b>8g of fat</b>. For <b>21 cents per serving</b>, this recipe <b>covers 2%</b> of your daily requirements of vitamins and minerals. If you have baking powder, vanillan extract, egg, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. 2 people have made this recipe and would make it again. From preparation to the plate, this recipe takes roughly <b>1 hour and 30 minutes</b>. Overall, this recipe earns a <b>very bad (but still fixable) spoonacular score of 10%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/chocolate-sandwich-cookies-homemade-oreos-507368">Chocolate Sandwich Cookies (Homemade Oreos)</a>, <a href="https://spoonacular.com/recipes/homemade-oreos-78891">Homemade Oreos</a>, and <a href="https://spoonacular.com/recipes/homemade-oreos-482872">Homemade Oreos</a>.',
    cuisines: [],
    dishTypes: ["dessert"],
    diets: [],
    occasions: [],
    instructions:
      "<ol><li>Set two racks in the middle of the oven. Preheat to 375F.</li><li>In a food processor, or bowl of an electric mixer, thoroughly mix the flour, cocoa, baking soda and powder, salt, and sugar. While pulsing, or on low speed, add the butter, and then the egg. Continue processing or mixing until dough comes together in a mass.</li><li>Take rounded teaspoons of batter and place on a parchment paper-lined baking sheet approximately two inches apart. (I started off with loonie sized chunks of dough which was too big. Its more like the size of a quarter. Remember, youre aiming for 50 to 60 of these individual wafers!) With moistened hands, slightly flatten the dough. Bake for 9 minutes, rotating once for even baking. Set baking sheets on a rack to cool.</li><li>To make the cream, place butter and shortening in a mixing bowl, and at low speed, gradually beat in the sugar and vanilla. Turn the mixer on high and beat for 2 to 3 minutes until filling is light and fluffy.</li><li>To assemble the cookies, in a pastry bag with a 1/2 inch, round tip, pipe teaspoon-size blobs of cream into the center of one cookie. Place another cookie, equal in size to the first, on top of the cream. Lightly press, to work the filling evenly to the outsides of the cookie. (I dont think its entirely necessary to use a pastry bag. You could just spoon some icing on and squeeze between two wafers.) Continue this process until all the cookies have been sandwiched with cream.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Set two racks in the middle of the oven. Preheat to 375F.In a food processor, or bowl of an electric mixer, thoroughly mix the flour, cocoa, baking soda and powder, salt, and sugar. While pulsing, or on low speed, add the butter, and then the egg. Continue processing or mixing until dough comes together in a mass.Take rounded teaspoons of batter and place on a parchment paper-lined baking sheet approximately two inches apart. (I started off with loonie sized chunks of dough which was too big. Its more like the size of a quarter. Remember, youre aiming for 50 to 60 of these individual wafers!) With moistened hands, slightly flatten the dough.",
            ingredients: [
              {
                id: 18372,
                name: "baking soda",
                localizedName: "baking soda",
                image: "white-powder.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 0,
                name: "wafer cookies",
                localizedName: "wafer cookies",
                image: "shortbread-cookies.jpg",
              },
              {
                id: 19165,
                name: "cocoa powder",
                localizedName: "cocoa powder",
                image: "cocoa-powder.png",
              },
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              {
                id: 19335,
                name: "sugar",
                localizedName: "sugar",
                image: "sugar-in-bowl.png",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
              {
                id: 1123,
                name: "egg",
                localizedName: "egg",
                image: "egg.png",
              },
            ],
            equipment: [
              {
                id: 404770,
                name: "baking paper",
                localizedName: "baking paper",
                image: "baking-paper.jpg",
              },
              {
                id: 404628,
                name: "hand mixer",
                localizedName: "hand mixer",
                image: "hand-mixer.png",
              },
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
              {
                id: 404727,
                name: "baking sheet",
                localizedName: "baking sheet",
                image: "baking-sheet.jpg",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
                temperature: { number: 375.0, unit: "Fahrenheit" },
              },
            ],
          },
          {
            number: 2,
            step: "Bake for 9 minutes, rotating once for even baking. Set baking sheets on a rack to cool.To make the cream, place butter and shortening in a mixing bowl, and at low speed, gradually beat in the sugar and vanilla. Turn the mixer on high and beat for 2 to 3 minutes until filling is light and fluffy.To assemble the cookies, in a pastry bag with a 1/2 inch, round tip, pipe teaspoon-size blobs of cream into the center of one cookie.",
            ingredients: [
              {
                id: 4615,
                name: "shortening",
                localizedName: "shortening",
                image: "shortening.jpg",
              },
              {
                id: 10118192,
                name: "cookies",
                localizedName: "cookies",
                image: "shortbread-cookies.jpg",
              },
              {
                id: 1052050,
                name: "vanilla",
                localizedName: "vanilla",
                image: "vanilla.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 19335,
                name: "sugar",
                localizedName: "sugar",
                image: "sugar-in-bowl.png",
              },
            ],
            equipment: [
              {
                id: 404727,
                name: "baking sheet",
                localizedName: "baking sheet",
                image: "baking-sheet.jpg",
              },
              {
                id: 405907,
                name: "mixing bowl",
                localizedName: "mixing bowl",
                image: "mixing-bowl.jpg",
              },
              {
                id: 404757,
                name: "pastry bag",
                localizedName: "pastry bag",
                image: "pastry-bag.jpg",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
            length: { number: 11, unit: "minutes" },
          },
          {
            number: 3,
            step: "Place another cookie, equal in size to the first, on top of the cream. Lightly press, to work the filling evenly to the outsides of the cookie. (I dont think its entirely necessary to use a pastry bag. You could just spoon some icing on and squeeze between two wafers.) Continue this process until all the cookies have been sandwiched with cream.",
            ingredients: [
              {
                id: 10118192,
                name: "cookies",
                localizedName: "cookies",
                image: "shortbread-cookies.jpg",
              },
              {
                id: 0,
                name: "wafer cookies",
                localizedName: "wafer cookies",
                image: "shortbread-cookies.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 10019230,
                name: "icing",
                localizedName: "icing",
                image: "frosting-or-icing.png",
              },
            ],
            equipment: [
              {
                id: 404757,
                name: "pastry bag",
                localizedName: "pastry bag",
                image: "pastry-bag.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/delicious-homemade-chocolate-oreos-641395",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 5,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 5,
    healthScore: 38,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 167.93,
    extendedIngredients: [
      {
        id: 12155,
        aisle: "Nuts;Baking",
        image: "walnuts.jpg",
        consistency: "SOLID",
        name: "walnuts",
        nameClean: "walnuts",
        original: "1 cup chopped, toasted walnuts",
        originalName: "chopped, toasted walnuts",
        amount: 1.0,
        unit: "cup",
        meta: ["toasted", "chopped"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 117.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 10311297,
        aisle: "Produce",
        image: "parsley.jpg",
        consistency: "SOLID",
        name: "parsley",
        nameClean: "flat leaf parsley",
        original:
          "2 cups finely chopped Italian parsley (approximately 2 bunches)",
        originalName:
          "finely chopped Italian parsley (approximately 2 bunches)",
        amount: 2.0,
        unit: "cups",
        meta: ["italian", "finely chopped", "(approximately 2 bunches)"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 120.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 9195,
        aisle: "Canned and Jarred",
        image: "olives-mixed.jpg",
        consistency: "SOLID",
        name: "niçoise olives",
        nameClean: "olives",
        original:
          "3/4 cup chopped, pitted kalamata, Greek, or niçoise olives (about 1 ¼ cups with pits)",
        originalName:
          "chopped, pitted kalamata, Greek, or niçoise olives (about 1 ¼ cups with pits)",
        amount: 0.75,
        unit: "cup",
        meta: ["with pits)", "pitted", "chopped"],
        measures: {
          us: { amount: 0.75, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 101.25,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "SOLID",
        name: "scallion",
        nameClean: "spring onions",
        original: "1/2 cup minced scallion (about 1 bunch)",
        originalName: "minced scallion (about 1 bunch)",
        amount: 0.5,
        unit: "cup",
        meta: ["minced", "( 1 bunch)"],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 50.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11529,
        aisle: "Produce",
        image: "tomato.png",
        consistency: "SOLID",
        name: "tomato",
        nameClean: "tomato",
        original: "1 cup peeled, seeded, and chopped tomato (2 large)",
        originalName: "peeled, seeded, and chopped tomato (2 large)",
        amount: 1.0,
        unit: "cup",
        meta: ["peeled", "seeded", "chopped", "(2 large)"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 149.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1034053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "extra virgin olive oil",
        nameClean: "extra virgin olive oil",
        original: "cup extra virgin olive oil",
        originalName: "extra virgin olive oil",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: {
            amount: 216.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 9152,
        aisle: "Produce",
        image: "lemon-juice.jpg",
        consistency: "LIQUID",
        name: "squeezed lemon juice",
        nameClean: "lemon juice",
        original: "cup fresh squeezed lemon juice",
        originalName: "fresh squeezed lemon juice",
        amount: 1.0,
        unit: "cup",
        meta: ["fresh"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: {
            amount: 244.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1012014,
        aisle: "Spices and Seasonings",
        image: "ground-cumin.jpg",
        consistency: "SOLID",
        name: "cumin powder",
        nameClean: "ground cumin",
        original: "1/2 teaspoon cumin powder",
        originalName: "cumin powder",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 10511819,
        aisle: "Produce",
        image: "red-chili.jpg",
        consistency: "SOLID",
        name: "chili flake",
        nameClean: "red chili pepper",
        original: "1/2 teaspoon red chili flake",
        originalName: "red chili flake",
        amount: 0.5,
        unit: "teaspoon",
        meta: ["red"],
        measures: {
          us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 1082047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "kosher salt and coarsely ground pepper",
        nameClean: "kosher salt",
        original: "Kosher salt and coarsely ground black pepper (to taste)",
        originalName: "Kosher salt and coarsely ground black pepper (to taste)",
        amount: 8.0,
        unit: "servings",
        meta: ["black", "to taste"],
        measures: {
          us: { amount: 8.0, unitShort: "servings", unitLong: "servings" },
          metric: {
            amount: 8.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
    ],
    id: 651823,
    title: "Middle Eastern Chopped Salad",
    readyInMinutes: 45,
    servings: 8,
    sourceUrl:
      "https://www.foodista.com/recipe/YWH5QKBS/middle-eastern-chopped-salad",
    image: "https://spoonacular.com/recipeImages/651823-556x370.jpg",
    imageType: "jpg",
    summary:
      'Middle Eastern Chopped Salad could be just the <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian</b> recipe you\'ve been looking for. One serving contains <b>180 calories</b>, <b>3g of protein</b>, and <b>17g of fat</b>. For <b>$1.68 per serving</b>, you get a hor d\'oeuvre that serves 8. 5 people have made this recipe and would make it again. Head to the store and pick up chili flake, parsley, kosher salt and coarsely ground pepper, and a few other things to make it today. Not a lot of people really liked this middl eastern dish. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 87%</b>, which is great. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/middle-eastern-chopped-salad-1345095">Middle Eastern Chopped Salad</a>, <a href="https://spoonacular.com/recipes/middle-eastern-chopped-salad-1313443">Middle Eastern Chopped Salad</a>, and <a href="https://spoonacular.com/recipes/middle-eastern-chopped-salad-1280851">Middle Eastern Chopped Salad</a>.',
    cuisines: ["Middle Eastern"],
    dishTypes: [
      "side dish",
      "antipasti",
      "salad",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "whole 30",
      "vegan",
    ],
    occasions: [],
    instructions:
      "Preheat the oven to 325 F.\nPlace the nuts on a baking sheet and toast for about 10 minutes until they begin to emit a toasted nut aroma. Cool completely before using the nuts in the recipe.\nRemove the stems from the parsley and mince either by hand or with quick pulses in a food processor. The parsley should be finely minced, but if you use a food processor be careful not to pure it. The parsley should form a fluffy base for the other textures.\nChop the olives, walnuts, and scallions by hand into a rough dice. Dice the prepared tomatoes and drain.\nCombine all of the chopped ingredients. Toss in a large wooden bowl with the olive oil, fresh lemon juice, cumin, and chili flakes. Season to taste with salt and black pepper.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat the oven to 325 F.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
                temperature: { number: 325.0, unit: "Fahrenheit" },
              },
            ],
          },
          {
            number: 2,
            step: "Place the nuts on a baking sheet and toast for about 10 minutes until they begin to emit a toasted nut aroma. Cool completely before using the nuts in the recipe.",
            ingredients: [
              {
                id: 0,
                name: "sandwich bread",
                localizedName: "sandwich bread",
                image: "white-bread.jpg",
              },
              {
                id: 12135,
                name: "nuts",
                localizedName: "nuts",
                image: "nuts-mixed.jpg",
              },
            ],
            equipment: [
              {
                id: 404727,
                name: "baking sheet",
                localizedName: "baking sheet",
                image: "baking-sheet.jpg",
              },
            ],
            length: { number: 10, unit: "minutes" },
          },
          {
            number: 3,
            step: "Remove the stems from the parsley and mince either by hand or with quick pulses in a food processor. The parsley should be finely minced, but if you use a food processor be careful not to pure it. The parsley should form a fluffy base for the other textures.",
            ingredients: [
              {
                id: 11297,
                name: "parsley",
                localizedName: "parsley",
                image: "parsley.jpg",
              },
              {
                id: 0,
                name: "ground meat",
                localizedName: "ground meat",
                image: "fresh-ground-beef.jpg",
              },
              { id: 0, name: "base", localizedName: "base", image: "" },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
            ],
          },
          {
            number: 4,
            step: "Chop the olives, walnuts, and scallions by hand into a rough dice. Dice the prepared tomatoes and drain.",
            ingredients: [
              {
                id: 11291,
                name: "green onions",
                localizedName: "green onions",
                image: "spring-onions.jpg",
              },
              {
                id: 11529,
                name: "tomato",
                localizedName: "tomato",
                image: "tomato.png",
              },
              {
                id: 12155,
                name: "walnuts",
                localizedName: "walnuts",
                image: "walnuts.jpg",
              },
              {
                id: 9195,
                name: "olives",
                localizedName: "olives",
                image: "olives-mixed.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Combine all of the chopped ingredients. Toss in a large wooden bowl with the olive oil, fresh lemon juice, cumin, and chili flakes. Season to taste with salt and black pepper.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 1032009,
                name: "red pepper flakes",
                localizedName: "red pepper flakes",
                image: "red-pepper-flakes.jpg",
              },
              {
                id: 9152,
                name: "lemon juice",
                localizedName: "lemon juice",
                image: "lemon-juice.jpg",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 1002014,
                name: "cumin",
                localizedName: "cumin",
                image: "ground-cumin.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/middle-eastern-chopped-salad-651823",
  },
  {
    license: "true",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3,
    healthScore: 100,
    creditsText: "foodista.com",
    sourceName: "foodista.com",
    pricePerServing: 382.96,
    extendedIngredients: [
      {
        id: 20035,
        aisle: "Pasta and Rice;Health Foods",
        image: "uncooked-quinoa.png",
        consistency: "SOLID",
        name: "quinoa",
        nameClean: "quinoa",
        original: "1 cup Quinoa",
        originalName: "Quinoa",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 170.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 medium Onion (diced)",
        originalName: "Onion (diced)",
        amount: 1.0,
        unit: "medium",
        meta: ["diced", "()"],
        measures: {
          us: { amount: 1.0, unitShort: "medium", unitLong: "medium" },
          metric: { amount: 1.0, unitShort: "medium", unitLong: "medium" },
        },
      },
      {
        id: 11233,
        aisle: "Produce",
        image: "kale.jpg",
        consistency: "SOLID",
        name: "kale",
        nameClean: "kale",
        original: "8 Leaves of Kale (stems removed and cut into ribbons)",
        originalName: "Kale (stems removed and cut into ribbons)",
        amount: 8.0,
        unit: "Leaves",
        meta: ["cut into ribbons)"],
        measures: {
          us: { amount: 8.0, unitShort: "leaf", unitLong: "leaves" },
          metric: { amount: 8.0, unitShort: "leaf", unitLong: "leaves" },
        },
      },
      {
        id: 10211215,
        aisle: "Produce",
        image: "garlic.jpg",
        consistency: "SOLID",
        name: "garlic cloves",
        nameClean: "whole garlic cloves",
        original: "5 Garlic Cloves (finely chopped)",
        originalName: "Garlic Cloves (finely chopped)",
        amount: 5.0,
        unit: "",
        meta: ["finely chopped", "()"],
        measures: {
          us: { amount: 5.0, unitShort: "", unitLong: "" },
          metric: { amount: 5.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "olive oil",
        nameClean: "olive oil",
        original: "3 tablespoons Olive Oil (divided)",
        originalName: "Olive Oil (divided)",
        amount: 3.0,
        unit: "tablespoons",
        meta: ["divided", "()"],
        measures: {
          us: { amount: 3.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 3.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 15076,
        aisle: "Seafood",
        image: "salmon.png",
        consistency: "SOLID",
        name: "poached salmon",
        nameClean: "salmon",
        original: "10 ounces Poached Salmon (flaked)*",
        originalName: "Poached Salmon (flaked)",
        amount: 10.0,
        unit: "ounces",
        meta: ["flaked", "()"],
        measures: {
          us: { amount: 10.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 283.495, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 6615,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "LIQUID",
        name: "vegetable stock",
        nameClean: "vegetable stock",
        original: "32 ounces Organic Vegetable Stock",
        originalName: "Organic Vegetable Stock",
        amount: 32.0,
        unit: "ounces",
        meta: ["organic"],
        measures: {
          us: { amount: 32.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 907.185, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "Salt",
        originalName: "Salt",
        amount: 4.0,
        unit: "servings",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "servings", unitLong: "servings" },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 10211821,
        aisle: "Produce",
        image: "bell-pepper-orange.png",
        consistency: "SOLID",
        name: "bell pepper",
        nameClean: "bell pepper",
        original: "Pepper",
        originalName: "Pepper",
        amount: 4.0,
        unit: "servings",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "servings", unitLong: "servings" },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
    ],
    id: 659109,
    title: "Salmon Quinoa Risotto",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: "https://www.foodista.com/recipe/KH5STR7N/salmon-quinoa-risotto",
    image: "https://spoonacular.com/recipeImages/659109-556x370.jpg",
    imageType: "jpg",
    summary:
      'Salmon Quinoa Risotto might be just the main course you are searching for. One serving contains <b>437 calories</b>, <b>25g of protein</b>, and <b>20g of fat</b>. This recipe serves 4. For <b>$3.83 per serving</b>, this recipe <b>covers 43%</b> of your daily requirements of vitamins and minerals. Head to the store and pick up quinoa, poached salmon, olive oil, and a few other things to make it today. It is a good option if you\'re following a <b>gluten free, dairy free, and pescatarian</b> diet. It is a <b>rather expensive</b> recipe for fans of Mediterranean food. 3 people found this recipe to be yummy and satisfying. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. It is brought to you by Foodista. Overall, this recipe earns an <b>outstanding spoonacular score of 94%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/salmon-quinoa-risotto-1360771">Salmon Quinoa Risotto</a>, <a href="https://spoonacular.com/recipes/salmon-quinoa-risotto-1288579">Salmon Quinoa Risotto</a>, and <a href="https://spoonacular.com/recipes/quinoa-risotto-with-salmon-and-kale-15276">Quinoa Risotto With Salmon And Kale</a>.',
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "pescatarian"],
    occasions: [],
    instructions:
      "In a 4 quart saucepan, heat 2 tablespoons of olive oil over medium high heat.\nWhen oil is shimmering, add diced onion.\nSaute onion until transparent.  Add quinoa to onion mixture and stir, to toast quinoa, for 2 minutes.\nAdd 1 cup of vegetable stock to quinoa and onions.\nStir until stock is absorbed.  Once stock is absorbed, add 1 cup of stock.\nContinue stirring until stock is absorbed.\nAdd remaining stock in 1/2 cup intervals, stirring until all stock is absorbed.\nRemove from heat.\nWhile preparing the onion quinoa mixture, heat 1 tablespoon of oil in a saute pan with chopped garlic (over medium high heat).\nOnce garlic is sizzling, add chopped kale to the pan.\nTurn kale to coat with oil and garlic.\nTurn kale mixture until fragrant (approximately 2 minutes).  Remove kale mixture from heat.\nOnce quinoa is complete, add kale and salmon.\nStir to combine.\nAdd salt and pepper to taste.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "In a 4 quart saucepan, heat 2 tablespoons of olive oil over medium high heat.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "When oil is shimmering, add diced onion.",
            ingredients: [
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Saute onion until transparent.",
            ingredients: [
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Add quinoa to onion mixture and stir, to toast quinoa, for 2 minutes.",
            ingredients: [
              {
                id: 20035,
                name: "quinoa",
                localizedName: "quinoa",
                image: "uncooked-quinoa.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 0,
                name: "sandwich bread",
                localizedName: "sandwich bread",
                image: "white-bread.jpg",
              },
            ],
            equipment: [],
            length: { number: 2, unit: "minutes" },
          },
          {
            number: 5,
            step: "Add 1 cup of vegetable stock to quinoa and onions.",
            ingredients: [
              {
                id: 6615,
                name: "vegetable stock",
                localizedName: "vegetable stock",
                image: "chicken-broth.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 20035,
                name: "quinoa",
                localizedName: "quinoa",
                image: "uncooked-quinoa.png",
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: "Stir until stock is absorbed.  Once stock is absorbed, add 1 cup of stock.",
            ingredients: [
              {
                id: 1006615,
                name: "stock",
                localizedName: "stock",
                image: "chicken-broth.png",
              },
            ],
            equipment: [],
          },
          {
            number: 7,
            step: "Continue stirring until stock is absorbed.",
            ingredients: [
              {
                id: 1006615,
                name: "stock",
                localizedName: "stock",
                image: "chicken-broth.png",
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Add remaining stock in 1/2 cup intervals, stirring until all stock is absorbed.",
            ingredients: [
              {
                id: 1006615,
                name: "stock",
                localizedName: "stock",
                image: "chicken-broth.png",
              },
            ],
            equipment: [],
          },
          {
            number: 9,
            step: "Remove from heat.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 10,
            step: "While preparing the onion quinoa mixture, heat 1 tablespoon of oil in a saute pan with chopped garlic (over medium high heat).",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 20035,
                name: "quinoa",
                localizedName: "quinoa",
                image: "uncooked-quinoa.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 11,
            step: "Once garlic is sizzling, add chopped kale to the pan.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11233,
                name: "kale",
                localizedName: "kale",
                image: "kale.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 12,
            step: "Turn kale to coat with oil and garlic.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11233,
                name: "kale",
                localizedName: "kale",
                image: "kale.jpg",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 13,
            step: "Turn kale mixture until fragrant (approximately 2 minutes).",
            ingredients: [
              {
                id: 11233,
                name: "kale",
                localizedName: "kale",
                image: "kale.jpg",
              },
            ],
            equipment: [],
            length: { number: 2, unit: "minutes" },
          },
          {
            number: 14,
            step: "Remove kale mixture from heat.",
            ingredients: [
              {
                id: 11233,
                name: "kale",
                localizedName: "kale",
                image: "kale.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 15,
            step: "Once quinoa is complete, add kale and salmon.",
            ingredients: [
              {
                id: 20035,
                name: "quinoa",
                localizedName: "quinoa",
                image: "uncooked-quinoa.png",
              },
              {
                id: 15076,
                name: "salmon",
                localizedName: "salmon",
                image: "salmon.png",
              },
              {
                id: 11233,
                name: "kale",
                localizedName: "kale",
                image: "kale.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 16,
            step: "Stir to combine.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 17,
            step: "Add salt and pepper to taste.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/salmon-quinoa-risotto-659109",
  },
  {
    license: "true",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 18,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 6,
    healthScore: 17,
    creditsText: "foodista.com",
    sourceName: "foodista.com",
    pricePerServing: 191.28,
    extendedIngredients: [
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "all purpose flour",
        nameClean: "wheat flour",
        original: "2 cups of All Purpose Flour",
        originalName: "All Purpose Flour",
        amount: 2.0,
        unit: "cups",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 250.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "1 tablespoon of Butter",
        originalName: "Butter",
        amount: 1.0,
        unit: "tablespoon",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "4 tablespoons of Butter",
        originalName: "Butter",
        amount: 4.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 1123,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg.png",
        consistency: "SOLID",
        name: "eggs",
        nameClean: "egg",
        original: "3 Large Eggs",
        originalName: "Large Eggs",
        amount: 3.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 3.0, unitShort: "", unitLong: "" },
          metric: { amount: 3.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 2044,
        aisle: "Produce;Spices and Seasonings",
        image: "basil.jpg",
        consistency: "SOLID",
        name: "basil",
        nameClean: "fresh basil",
        original: "1 bunch of Fresh Basil, Chopped",
        originalName: "Fresh Basil, Chopped",
        amount: 1.0,
        unit: "bunch",
        meta: ["fresh", "chopped"],
        measures: {
          us: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
          metric: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "2 cloves of Garlic",
        originalName: "Garlic",
        amount: 2.0,
        unit: "cloves",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "cloves", unitLong: "cloves" },
          metric: { amount: 2.0, unitShort: "cloves", unitLong: "cloves" },
        },
      },
      {
        id: 11260,
        aisle: "Produce",
        image: "mushrooms-white.jpg",
        consistency: "SOLID",
        name: "mushrooms",
        nameClean: "fresh mushrooms",
        original: "5 ounces Mushrooms, Diced",
        originalName: "Mushrooms, Diced",
        amount: 5.0,
        unit: "ounces",
        meta: ["diced"],
        measures: {
          us: { amount: 5.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 141.748, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1/2 Onion, Diced",
        originalName: "Onion, Diced",
        amount: 0.5,
        unit: "",
        meta: ["diced"],
        measures: {
          us: { amount: 0.5, unitShort: "", unitLong: "" },
          metric: { amount: 0.5, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 2027,
        aisle: "Produce;Spices and Seasonings",
        image: "oregano.jpg",
        consistency: "SOLID",
        name: "oregano",
        nameClean: "oregano",
        original: "1 teaspoon of Oregano",
        originalName: "Oregano",
        amount: 1.0,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          metric: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
        },
      },
      {
        id: 10010123,
        aisle: "Meat",
        image: "proscuitto.jpg",
        consistency: "SOLID",
        name: "prosciutto",
        nameClean: "prosciutto",
        original: "4 ounces prosciutto, thinly sliced",
        originalName: "prosciutto, thinly sliced",
        amount: 4.0,
        unit: "ounces",
        meta: ["thinly sliced"],
        measures: {
          us: { amount: 4.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 113.398, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "1/8 teaspoon Salt",
        originalName: "Salt",
        amount: 0.125,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.125, unitShort: "tsps", unitLong: "teaspoons" },
          metric: {
            amount: 0.125,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 10011457,
        aisle: "Produce",
        image: "spinach.jpg",
        consistency: "SOLID",
        name: "spinach",
        nameClean: "spinach",
        original: "3 ounces Fresh Spinach",
        originalName: "Fresh Spinach",
        amount: 3.0,
        unit: "ounces",
        meta: ["fresh"],
        measures: {
          us: { amount: 3.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 85.049, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    id: 657159,
    title: "Prosciutto and Mushroom Ravioli With Basil Browned Butter Sauce",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "http://www.foodista.com/recipe/FM8XPRRP/prosciutto-and-mushroom-ravioli-with-basil-browned-butter-sauce",
    image: "https://spoonacular.com/recipeImages/657159-556x370.jpg",
    imageType: "jpg",
    summary:
      'If you want to add more <b>Mediterranean</b> recipes to your recipe box, Prosciutto and Mushroom Ravioli With Basil Browned Butter Sauce might be a recipe you should try. This main course has <b>541 calories</b>, <b>16g of protein</b>, and <b>29g of fat</b> per serving. This recipe serves 4. For <b>$1.91 per serving</b>, this recipe <b>covers 25%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista has 6 fans. Head to the store and pick up all purpose flour, oregano, butter, and a few other things to make it today. From preparation to the plate, this recipe takes around <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 65%</b>, which is solid. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/prosciutto-and-mushroom-ravioli-with-basil-browned-butter-sauce-1592023">Prosciutto and Mushroom Ravioli With Basil Browned Butter Sauce</a>, <a href="https://spoonacular.com/recipes/prosciutto-and-mushroom-ravioli-with-basil-browned-butter-sauce-1382779">Prosciutto and Mushroom Ravioli With Basil Browned Butter Sauce</a>, and <a href="https://spoonacular.com/recipes/browned-butter-mushroom-ravioli-with-sage-574170">Browned Butter Mushroom Ravioli with Sage</a>.',
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: [],
    instructions:
      "<ol><li>We'll start out by making the dough for our ravioli. Add to a food processor all of your ravioli ingredients.</li><li>Run the processor and mix the ingredients up well. If the dough looks like pebbles, it's a touch too dry. Add about 1/2-1 tsp of water and mix again. It should form a nice ball of dough. Once your dough is mixed, bring it out of the processor and knead it for a few minutes.</li><li>Cover your ball of pasta dough with plastic wrap and let it rest for a good twenty minutes.</li><li>While your dough is resting, let's whip up the tasty filling. Grab your skillet and heat up the butter on medium heat. Now add in the garlic.</li><li>Next we'll add in the proscuitto, onions and mushrooms.</li><li>Let it cook up for a minute or two and then add in the salt and oregano. Give it a swirl or two around the pan to mix in and then add in your spinach.</li><li>Let the spinach wilt down completely and then remove the mixture from the heat.</li><li>Now it's time to grab your well rested pasta dough and pop out some ravioli.</li><li>Rip off about a sixth of the ball and run it through your pasta maker (or hand roll it) to the desired thinness.</li><li>If you have a ravioli cutter you can use that, or you can use a glass to cut circles, or you can do like we did and use a cookie cutter to make fun shapes celebrating the holiday.</li><li>After you have your ravioli cut out, you'll drop a good teaspoonful of the prosciutto mixture into the center of the pasta.</li><li>Brush the edges with an egg wash (the egg white from one egg) and place another pasta piece over the top. Seal the edges with your fingers, a fork, or whatever puts a smile on your face.</li><li>Grab a pot, fill it up with water and set it to boil. The pasta will cook up quick (it will float when cooked)</li><li>Grab another pan, drop the butter into it and cook it on medium until it turns a beautiful golden brown and gives off a lovely nutty smell. At this point you'll turn the heat down just a notch and add in your garlic.</li><li>Now drop in your chopped basil, give it a swirl or two to let the basil wilt and your butter sauce is ready to rumble.</li><li>Drain your cooked up ravioli, dump them in the butter sauce and get them good and coated.</li><li>Serve them up with a little grated Parmesan or Romano over the top.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "We'll start out by making the dough for our ravioli.",
            ingredients: [
              {
                id: 93832,
                name: "ravioli",
                localizedName: "ravioli",
                image: "ravioli.png",
              },
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Add to a food processor all of your ravioli ingredients.Run the processor and mix the ingredients up well. If the dough looks like pebbles, it's a touch too dry.",
            ingredients: [
              {
                id: 93832,
                name: "ravioli",
                localizedName: "ravioli",
                image: "ravioli.png",
              },
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
            ],
          },
          {
            number: 3,
            step: "Add about 1/2-1 tsp of water and mix again. It should form a nice ball of dough. Once your dough is mixed, bring it out of the processor and knead it for a few minutes.Cover your ball of pasta dough with plastic wrap and let it rest for a good twenty minutes.While your dough is resting, let's whip up the tasty filling. Grab your skillet and heat up the butter on medium heat. Now add in the garlic.Next we'll add in the proscuitto, onions and mushrooms.",
            ingredients: [
              {
                id: 10118334,
                name: "pasta dough",
                localizedName: "pasta dough",
                image: "dough.jpg",
              },
              {
                id: 10010123,
                name: "prosciutto",
                localizedName: "prosciutto",
                image: "proscuitto.jpg",
              },
              {
                id: 11260,
                name: "mushrooms",
                localizedName: "mushrooms",
                image: "mushrooms.png",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 10018364,
                name: "wrap",
                localizedName: "wrap",
                image: "flour-tortilla.jpg",
              },
            ],
            equipment: [
              {
                id: 404730,
                name: "plastic wrap",
                localizedName: "plastic wrap",
                image: "plastic-wrap.jpg",
              },
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
            length: { number: 20, unit: "minutes" },
          },
          {
            number: 4,
            step: "Let it cook up for a minute or two and then add in the salt and oregano. Give it a swirl or two around the pan to mix in and then add in your spinach.",
            ingredients: [
              {
                id: 2027,
                name: "oregano",
                localizedName: "oregano",
                image: "oregano.jpg",
              },
              {
                id: 10011457,
                name: "spinach",
                localizedName: "spinach",
                image: "spinach.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 5,
            step: "Let the spinach wilt down completely and then remove the mixture from the heat.Now it's time to grab your well rested pasta dough and pop out some ravioli.Rip off about a sixth of the ball and run it through your pasta maker (or hand roll it) to the desired thinness.If you have a ravioli cutter you can use that, or you can use a glass to cut circles, or you can do like we did and use a cookie cutter to make fun shapes celebrating the holiday.After you have your ravioli cut out, you'll drop a good teaspoonful of the prosciutto mixture into the center of the pasta.",
            ingredients: [
              {
                id: 10118334,
                name: "pasta dough",
                localizedName: "pasta dough",
                image: "dough.jpg",
              },
              {
                id: 10010123,
                name: "prosciutto",
                localizedName: "prosciutto",
                image: "proscuitto.jpg",
              },
              {
                id: 93832,
                name: "ravioli",
                localizedName: "ravioli",
                image: "ravioli.png",
              },
              {
                id: 10011457,
                name: "spinach",
                localizedName: "spinach",
                image: "spinach.jpg",
              },
              {
                id: 10118192,
                name: "cookies",
                localizedName: "cookies",
                image: "shortbread-cookies.jpg",
              },
              {
                id: 20420,
                name: "pasta",
                localizedName: "pasta",
                image: "fusilli.jpg",
              },
              {
                id: 0,
                name: "roll",
                localizedName: "roll",
                image: "dinner-yeast-rolls.jpg",
              },
              {
                id: 0,
                name: "pop",
                localizedName: "soft drink",
                image: "",
              },
            ],
            equipment: [
              {
                id: 221429,
                name: "cookie cutter",
                localizedName: "cookie cutter",
                image: "cookie-cutters.jpg",
              },
              {
                id: 406908,
                name: "pasta machine",
                localizedName: "pasta machine",
                image: "pasta-machine.jpg",
              },
            ],
          },
          {
            number: 6,
            step: "Brush the edges with an egg wash (the egg white from one egg) and place another pasta piece over the top. Seal the edges with your fingers, a fork, or whatever puts a smile on your face.Grab a pot, fill it up with water and set it to boil. The pasta will cook up quick (it will float when cooked)Grab another pan, drop the butter into it and cook it on medium until it turns a beautiful golden brown and gives off a lovely nutty smell. At this point you'll turn the heat down just a notch and add in your garlic.Now drop in your chopped basil, give it a swirl or two to let the basil wilt and your butter sauce is ready to rumble.",
            ingredients: [
              {
                id: 1124,
                name: "egg whites",
                localizedName: "egg whites",
                image: "egg-white.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 2044,
                name: "basil",
                localizedName: "basil",
                image: "basil.jpg",
              },
              {
                id: 20420,
                name: "pasta",
                localizedName: "pasta",
                image: "fusilli.jpg",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 1123,
                name: "egg",
                localizedName: "egg",
                image: "egg.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 7,
            step: "Drain your cooked up ravioli, dump them in the butter sauce and get them good and coated.",
            ingredients: [
              {
                id: 93832,
                name: "ravioli",
                localizedName: "ravioli",
                image: "ravioli.png",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Serve them up with a little grated Parmesan or Romano over the top.",
            ingredients: [
              {
                id: 1033,
                name: "parmesan",
                localizedName: "parmesan",
                image: "parmesan.jpg",
              },
              {
                id: 1038,
                name: "romano cheese",
                localizedName: "romano cheese",
                image: "parmesan.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/prosciutto-and-mushroom-ravioli-with-basil-browned-butter-sauce-657159",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 13,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 5,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 175.93,
    extendedIngredients: [
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "1 tablespoon butter",
        originalName: "butter",
        amount: 1.0,
        unit: "tablespoon",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 1016080,
        aisle: "Canned and Jarred",
        image: "stock-powder.png",
        consistency: "SOLID",
        name: "granulated chicken stock powder",
        nameClean: "chicken bouillon powder",
        original: "1/2 teaspoon granulated chicken stock powder",
        originalName: "granulated chicken stock powder",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 20027,
        aisle: "Baking",
        image: "white-powder.jpg",
        consistency: "SOLID",
        name: "cornstarch",
        nameClean: "corn starch",
        original: "1 tablespoon cornstarch",
        originalName: "cornstarch",
        amount: 1.0,
        unit: "tablespoon",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 11209,
        aisle: "Produce",
        image: "eggplant.png",
        consistency: "SOLID",
        name: "eggplant",
        nameClean: "eggplant",
        original: "1 eggplant",
        originalName: "eggplant",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "wheat flour",
        original: "2 tablespoons all-purpose flour",
        originalName: "all-purpose flour",
        amount: 2.0,
        unit: "tablespoons",
        meta: ["all-purpose"],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "1 clove garlic, pressed",
        originalName: "garlic, pressed",
        amount: 1.0,
        unit: "clove",
        meta: ["pressed"],
        measures: {
          us: { amount: 1.0, unitShort: "clove", unitLong: "clove" },
          metric: { amount: 1.0, unitShort: "clove", unitLong: "clove" },
        },
      },
      {
        id: 1053,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "LIQUID",
        name: "heavy cream",
        nameClean: "cream",
        original: "1 tablespoon heavy cream",
        originalName: "heavy cream",
        amount: 1.0,
        unit: "tablespoon",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 1077,
        aisle: "Milk, Eggs, Other Dairy",
        image: "milk.png",
        consistency: "LIQUID",
        name: "milk",
        nameClean: "milk",
        original: "3/4 cup milk (room temperature)",
        originalName: "milk (room temperature)",
        amount: 0.75,
        unit: "cup",
        meta: ["room temperature", "()"],
        measures: {
          us: { amount: 0.75, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 183.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 16112,
        aisle: "Ethnic Foods",
        image: "miso.jpg",
        consistency: "SOLID",
        name: "miso",
        nameClean: "miso",
        original: "4 tablespoons miso",
        originalName: "miso",
        amount: 4.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 1032,
        aisle: "Cheese",
        image: "parmesan.jpg",
        consistency: "LIQUID",
        name: "parmesan cheese",
        nameClean: "grated parmesan cheese",
        original: "3/4 cup grated parmesan cheese",
        originalName: "grated parmesan cheese",
        amount: 0.75,
        unit: "cup",
        meta: ["grated"],
        measures: {
          us: { amount: 0.75, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 75.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "salt and pepper to taste",
        originalName: "salt and pepper to taste",
        amount: 4.0,
        unit: "servings",
        meta: ["to taste"],
        measures: {
          us: { amount: 4.0, unitShort: "servings", unitLong: "servings" },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 16213,
        aisle: "Refrigerated;Produce;Ethnic Foods",
        image: "tofu.png",
        consistency: "SOLID",
        name: "tofu",
        nameClean: "tofu",
        original: "3/4 cup soft tofu",
        originalName: "soft tofu",
        amount: 0.75,
        unit: "cup",
        meta: ["soft"],
        measures: {
          us: { amount: 0.75, unitShort: "cups", unitLong: "cups" },
          metric: {
            amount: 186.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 4669,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vegetable-oil.jpg",
        consistency: "LIQUID",
        name: "vegetable oil",
        nameClean: "vegetable oil",
        original: "5 tablespoons vegetable oil",
        originalName: "vegetable oil",
        amount: 5.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: { amount: 5.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 5.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
    ],
    id: 652059,
    title: "Miso Eggplant Gratin",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: "http://www.foodista.com/recipe/3LN2F2VC/miso-eggplant-gratin",
    image: "https://spoonacular.com/recipeImages/652059-556x370.jpg",
    imageType: "jpg",
    summary:
      'Miso Eggplant Gratin requires roughly <b>45 minutes</b> from start to finish. This recipe serves 4. This side dish has <b>419 calories</b>, <b>15g of protein</b>, and <b>31g of fat</b> per serving. For <b>$1.76 per serving</b>, this recipe <b>covers 13%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista requires milk, granulated chicken stock powder, flour, and tofu. This recipe is liked by 2 foodies and cooks. With a spoonacular <b>score of 33%</b>, this dish is not so amazing. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/miso-glazed-eggplant-nasu-miso-23423">Miso-Glazed Eggplant (Nasu Miso)</a>, <a href="https://spoonacular.com/recipes/miso-eggplant-103351">Miso Eggplant</a>, and <a href="https://spoonacular.com/recipes/stuffed-miso-eggplant-604088">Stuffed Miso Eggplant</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [],
    occasions: [],
    instructions:
      "<ol><li>Preheat the oven to 450 F.</li><li>Cut the eggplant into bite size pieces and soak in water for 5 minutes.</li><li>Drain and pat dry.</li><li>Heat the oil in a pan on medium heat.</li><li>Add the eggplant pieces and brown on both sides.</li><li>Season with garlic, salt and pepper and hold.</li><li>To make the miso-tofu sauce, drain the tofu in a seive.</li><li>Sift together flour and cornstarch in a microwavable bowl.</li><li>Slowly add milk to the flour mixture.</li><li>Microwave on medium for 2 1/2 minutes.</li><li>Whisk the mixture to a smooth paste.</li><li>Add butter, stock powder, and heavy cream and mix thoroughly.</li><li>While the mixture is still hot, stir in miso and crumble the tofu into the sauce.  Mix till you have a thick paste-like consistency.</li><li>Pour half of the tofu-miso sauce into a casserole dish, cover with cooked eggplant and sprinkle half of the cheese on top.</li><li>Pour the remaining sauce into the dish and top with the remaining cheese.</li><li>Bake for 20 minutes until the gratin is bubbling and golden brown in color.</li><li>Serve with rice.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat the oven to 450 F.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
                temperature: { number: 450.0, unit: "Fahrenheit" },
              },
            ],
          },
          {
            number: 2,
            step: "Cut the eggplant into bite size pieces and soak in water for 5 minutes.",
            ingredients: [
              {
                id: 11209,
                name: "eggplant",
                localizedName: "eggplant",
                image: "eggplant.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 3,
            step: "Drain and pat dry.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 4,
            step: "Heat the oil in a pan on medium heat.",
            ingredients: [
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 5,
            step: "Add the eggplant pieces and brown on both sides.Season with garlic, salt and pepper and hold.To make the miso-tofu sauce, drain the tofu in a seive.Sift together flour and cornstarch in a microwavable bowl.Slowly add milk to the flour mixture.Microwave on medium for 2 1/2 minutes.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 20027,
                name: "corn starch",
                localizedName: "corn starch",
                image: "white-powder.jpg",
              },
              {
                id: 11209,
                name: "eggplant",
                localizedName: "eggplant",
                image: "eggplant.png",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
              {
                id: 16112,
                name: "miso",
                localizedName: "miso",
                image: "miso.jpg",
              },
              {
                id: 16213,
                name: "tofu",
                localizedName: "tofu",
                image: "tofu.png",
              },
            ],
            equipment: [
              {
                id: 404762,
                name: "microwave",
                localizedName: "microwave",
                image: "microwave.jpg",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
            length: { number: 2, unit: "minutes" },
          },
          {
            number: 6,
            step: "Whisk the mixture to a smooth paste.",
            ingredients: [],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image: "whisk.png",
              },
            ],
          },
          {
            number: 7,
            step: "Add butter, stock powder, and heavy cream and mix thoroughly.While the mixture is still hot, stir in miso and crumble the tofu into the sauce.",
            ingredients: [
              {
                id: 1016075,
                name: "stock powder",
                localizedName: "stock powder",
                image: "stock-powder.png",
              },
              {
                id: 1053,
                name: "heavy cream",
                localizedName: "heavy cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              {
                id: 16112,
                name: "miso",
                localizedName: "miso",
                image: "miso.jpg",
              },
              {
                id: 16213,
                name: "tofu",
                localizedName: "tofu",
                image: "tofu.png",
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Mix till you have a thick paste-like consistency.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 9,
            step: "Pour half of the tofu-miso sauce into a casserole dish, cover with cooked eggplant and sprinkle half of the cheese on top.",
            ingredients: [
              {
                id: 11209,
                name: "eggplant",
                localizedName: "eggplant",
                image: "eggplant.png",
              },
              {
                id: 1041009,
                name: "cheese",
                localizedName: "cheese",
                image: "cheddar-cheese.png",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              {
                id: 16112,
                name: "miso",
                localizedName: "miso",
                image: "miso.jpg",
              },
              {
                id: 16213,
                name: "tofu",
                localizedName: "tofu",
                image: "tofu.png",
              },
            ],
            equipment: [
              {
                id: 404635,
                name: "casserole dish",
                localizedName: "casserole dish",
                image: "casserole-dish.png",
              },
            ],
          },
          {
            number: 10,
            step: "Pour the remaining sauce into the dish and top with the remaining cheese.",
            ingredients: [
              {
                id: 1041009,
                name: "cheese",
                localizedName: "cheese",
                image: "cheddar-cheese.png",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
            ],
            equipment: [],
          },
          {
            number: 11,
            step: "Bake for 20 minutes until the gratin is bubbling and golden brown in color.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: { number: 20, unit: "minutes" },
          },
          {
            number: 12,
            step: "Serve with rice.",
            ingredients: [
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: "https://spoonacular.com/miso-eggplant-gratin-652059",
  },
];

export default randomRecipes;
